version: "1"
rules:
  - base: master
    upstream: prettier:master
    mergeMethod: none
    mergeUnstable: false
    reviewers:
      - "@syncier/infrastructure-team"

label: "PR :arrow_heading_down:"
